apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-app-deployment
spec:
  # 🚀 AUTO-HEALING: Chạy 2 bản sao (Replicas). 
  # Nếu 1 con chết, K8s tự dựng lại con mới ngay.
  replicas: 2
  selector:
    matchLabels:
      app: micro-app
  template:
    metadata:
      labels:
        app: micro-app
    spec:
      containers:
      - name: micro-app
        image: huynguyen101/micro-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # 🛡️ HEALTH CHECK: K8s dùng cái này để soi xem app có bị treo không
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: micro-app-service
spec:
  selector:
    app: micro-app
  ports:
    - protocol: TCP
      port: 80        # Cổng bên ngoài nhìn vào
      targetPort: 5000 # Cổng bên trong container
  type: LoadBalancer # K3s sẽ tự cấp một IP để Huy truy cập