- name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: itwasmehyu/micro-app:latest, itwasmehyu/micro-app:${{ github.sha }}