- name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: huynguyen101/micro-app:latest, huynguyen101/micro-app:${{ github.sha }}